#!/usr/bin/env bash
# Script pour configurer un serveur Ubuntu

HOSTS_FILE="/etc/hosts"

if [ "$EUID" -ne 0 ]; then
  exit 1
fi

cp "$HOSTS_FILE" "$HOSTS_FILE.bak"

sed -i '/[[:space:]]localhost$/d' "$HOSTS_FILE"
sed -i '/[[:space:]]facebook\.com$/d' "$HOSTS_FILE"

echo "127.0.0.2	localhost" >> "$HOSTS_FILE"
echo "8.8.8.8	facebook.com" >> "$HOSTS_FILE"
