#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

sudo sed -i '/[[:space:]]localhost$/d' /etc/hosts
sudo sed -i '/[[:space:]]facebook.com$/d' /etc/hosts
echo "127.0.0.2	localhost" | sudo tee -a /etc/hosts >/dev/null
echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts >/dev/null