#!/usr/bin/env bash
# Bash script that displays all active non-Docker IPv4 IPs on the machine it’s executed on.

ip -o -4 addr show | awk '{print $4}' | cut -d/ -f1 | grep -vE '^172\.1[6789]\.' | grep -v '^$'
